client.c File Reference
This file implements a `very` simple sample client.
#include <errno.h>
*
#include <stdio.h>
*
#include <string.h>
*
#include `storage.h`
*
#include `utils.h`
*
Functions
int main (int argc, char *argv[])
Start a client to interact with the storage server.
Variables
FILE * ClientFile
This is just a minimal stub implementation. You should modify it according to your design.
Detailed Description
This file implements a `very` simple sample client. The client connects to the server, running at SERVERHOST:SERVERPORT and performs a number of storage_* operations. If there are errors, the client exists.
Definition in file client.c.
Function Documentation
int main (int argc, char * argv[])
Start a client to interact with the storage server.
If connect is successful, the client performs a storage_set/get() on TABLE and KEY and outputs the results on stdout. Finally, it exists after disconnecting from the server.
Definition at line 24 of file client.c.
References ClientFile, logger(), MAX_CONFIG_LINE_LEN, MAX_ENC_PASSWORD_LEN, MAX_HOST_LEN, MAX_KEY_LEN, MAX_TABLE_LEN, MAX_USERNAME_LEN, storage_auth(), storage_connect(), storage_disconnect(), storage_get(), storage_set(), and storage_record::value.