storage.c File Reference
This file contains the implementation of the storage server interface as specified in storage.h.
#include <stdio.h>
*
#include <unistd.h>
*
#include <string.h>
*
#include <sys/types.h>
*
#include <sys/socket.h>
*
#include <netdb.h>
*
#include `storage.h`
*
#include `utils.h`
*
Functions
void * storage_connect (const char *hostname, const int port)
Establish a connection to the server.
int storage_auth (const char *username, const char *passwd, void *conn)
This is just a minimal stub implementation. You should modify it according to your design.
int storage_get (const char *table, const char *key, struct storage_record *record, void *conn)
This is just a minimal stub implementation. You should modify it according to your design.
int storage_set (const char *table, const char *key, struct storage_record *record, void *conn)
This is just a minimal stub implementation. You should modify it according to your design.
int storage_disconnect (void *conn)
This is just a minimal stub implementation. You should modify it according to your design.
Variables
FILE * ClientFile
This is just a minimal stub implementation. You should modify it according to your design.
Detailed Description
This file contains the implementation of the storage server interface as specified in storage.h.
Definition in file storage.c.
Function Documentation
int storage_auth (const char * username, const char * passwd, void * conn)
This is just a minimal stub implementation. You should modify it according to your design.
Authenticate the client's connection to the server.
Definition at line 70 of file storage.c.
References ClientFile, generate_encrypted_password(), logger(), MAX_CMD_LEN, recvline(), and sendall().
Referenced by main().
void* storage_connect (const char * hostname, const int port)
Establish a connection to the server.
Parameters
hostname The IP address or hostname of the server.
port The TCP port of the server.
Returns
If successful, return a pointer to a data structure that represents a connection to the server. Otherwise return NULL.
On error, errno will be set to one of the following, as appropriate: ERR_INVALID_PARAM, ERR_CONNECTION_FAIL, or ERR_UNKNOWN.
Definition at line 27 of file storage.c.
References ClientFile, logger(), and MAX_PORT_LEN.
Referenced by main().
int storage_disconnect (void * conn)
This is just a minimal stub implementation. You should modify it according to your design.
Close the connection to the server.
Definition at line 170 of file storage.c.
Referenced by main().
int storage_get (const char * table, const char * key, struct storage_record * record, void * conn)
This is just a minimal stub implementation. You should modify it according to your design.
Retrieve the value associated with a key in a table.
Definition at line 104 of file storage.c.
References ClientFile, logger(), MAX_CMD_LEN, recvline(), sendall(), and storage_record::value.
Referenced by main().
int storage_set (const char * table, const char * key, struct storage_record * record, void * conn)
This is just a minimal stub implementation. You should modify it according to your design.
Store a key/value pair in a table.
Definition at line 138 of file storage.c.
References ClientFile, logger(), MAX_CMD_LEN, recvline(), sendall(), and storage_record::value.
Referenced by main().